### ISSUE TITLE
ListView 请支持该必要组件

### ISSUE THREAD

**Issue by aapelismith** [NSFI/fishd-mobile#10]
ListView 请支持该必要组件

**Comment by codedart2018** [comment]
＋111　上拉加载下拉刷新太重要了。少了这个基本都没法用。

**Comment by codedart2018** [comment]
3月12号提的　马上7月份了也没有回音，这个组件是不是也没啥人管呀！

**Comment by aapelismith** [comment]
@codedart2018  撤了， 又一个KPI项目, github基本没人回应, 放弃吧

**Comment by codedart2018** [comment]
> @codedart2018 撤了， 又一个KPI项目, github基本没人回应, 放弃吧

确实kpi　目前看来react端跟着京东Taro混吧。至少这个还是一直稳定的

**Comment by hangaoke1** [comment]
> > @codedart2018 撤了， 又一个KPI项目, github基本没人回应, 放弃吧
> 
> 确实kpi　目前看来react端跟着京东Taro混吧。至少这个还是一直稳定的

非常抱歉，感谢建议

**Comment by hangaoke1** [comment]
版本1.0.3已支持，[ListView组件](https://nsfi.github.io/fishd-mobile-site/index.html#/zh-CN/components/listView)、[PullRefresh组件](https://nsfi.github.io/fishd-mobile-site/index.html#/zh-CN/components/pullRefresh)
