### ISSUE TITLE
求原理解析～

### ISSUE THREAD

**Issue by amazingliyuzhao** [NSFI/fishd-mobile#37]
怎么动态将内容生成ifream 能私聊下说一下原理吗，

**Comment by hangaoke1** [comment]
iframe通信 + react动态挂载
挂载部分原理：https://github.com/NSFI/fishd-mobile/blob/master/site/mobile/pages/Demo.js#L65
通讯部分原理：
https://github.com/NSFI/fishd-mobile/blob/master/site/mobile/lib/iframe.js
https://github.com/NSFI/fishd-mobile/blob/master/site/desktop/lib/iframe.js
